name: docker build & push

on:
  create:
    tags: 'v*'
  push:
    branches: [ main ]

jobs:
  release:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Dockerhub login
       env:
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       run: echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
     - name: Set up Docker Buildx
       id: buildx
       uses: crazy-max/ghaction-docker-buildx@v1
       with:
         version: latest
     - name: Add permissions
       run: chmod +x script.sh
     - name: Multi arch build
       run: |
         if [[ ${GITHUB_REF} == *"refs/tags"* ]]; 
         then
           docker buildx build --platform=linux/arm/v7,linux/arm64/v8,linux/amd64 -t fabiolune/dockerhub-image-remover:latest -t fabiolune/dockerhub-image-remover:${GITHUB_REF#refs/tags/v} --push .
         else 
           docker buildx build --platform=linux/arm/v7,linux/arm64/v8,linux/amd64 -t fabiolune/dockerhub-image-remover:latest --push .
         fi
